apiVersion: v1
kind: Service
metadata:
  name: cats-vs-dogs-api-service
spec:
  type: NodePort
  selector:
    app: cats-vs-dogs-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
